---
- name: SnapMirror Quiesce and Break for all volumes on SVM2
  hosts: localhost
  gather_facts: no
  vars:
    target_host: XYZ
    target_vserver: SVM2
  tasks:
    - name: Login to target host XYZ
      netapp.ontap.na_ontap_command:
        hostname: "{{ target_host }}"
        username: "{{ target_username }}"
        password: "{{ target_password }}"
        command: 'version'
      register: login_target

    - name: Collect all volumes from SVM2
      netapp.ontap.na_ontap_volume:
        hostname: "{{ target_host }}"
        username: "{{ target_username }}"
        password: "{{ target_password }}"
        vserver: "{{ target_vserver }}"
      register: volumes

    - name: Filter volumes starting with dat_ and not containing root
      set_fact:
        filtered_volumes: >-
          {{ volumes.results | selectattr('name', 'match', '^dat_.*') | rejectattr('name', 'search', 'root') | list }}

    - name: Get SnapMirror relationships for filtered volumes
      netapp.ontap.na_ontap_snapmirror:
        hostname: "{{ target_host }}"
        username: "{{ target_username }}"
        password: "{{ target_password }}"
        dest_vserver: "{{ target_vserver }}"
      register: snapmirrors

    - name: Filter SnapMirror relationships for the filtered volumes
      set_fact:
        filtered_snapmirrors: >-
          {{ snapmirrors.results | selectattr('destination.volume', 'in', filtered_volumes | map(attribute='name') | list) | list }}

    - name: Quiesce SnapMirror relationships for filtered volumes
      netapp.ontap.na_ontap_snapmirror:
        hostname: "{{ target_host }}"
        username: "{{ target_username }}"
        password: "{{ target_password }}"
        dest_vserver: "{{ target_vserver }}"
        dest_volume: "{{ item.destination.volume }}"
        state: quiesced
      loop: "{{ filtered_snapmirrors }}"

    - name: Break SnapMirror relationships for filtered volumes
      netapp.ontap.na_ontap_snapmirror:
        hostname: "{{ target_host }}"
        username: "{{ target_username }}"
        password: "{{ target_password }}"
        dest_vserver: "{{ target_vserver }}"
        dest_volume: "{{ item.destination.volume }}"
        state: broken
      loop: "{{ filtered_snapmirrors }}"
