---
- name: Update SnapMirror relationships for all volumes from SVM2
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Login to source host ABC
      netapp.ontap.na_ontap_command:
        hostname: "{{ source_host }}"
        username: "{{ source_username }}"
        password: "{{ source_password }}"
        command: 'version'
      register: login_source

    - name: Collect all volumes from SVM1
      netapp.ontap.na_ontap_volume:
        hostname: "{{ source_host }}"
        username: "{{ source_username }}"
        password: "{{ source_password }}"
        vserver: "{{ source_vserver }}"
      register: volumes

    - name: Filter volumes starting with dat_ and not containing root
      set_fact:
        filtered_volumes: >-
          {{ volumes.results | selectattr('name', 'match', '^dat_.*') | rejectattr('name', 'search', 'root') | list }}

    - name: Create snapshot "failover" on SVM1 volumes
      netapp.ontap.na_ontap_snapshot:
        hostname: "{{ source_host }}"
        username: "{{ source_username }}"
        password: "{{ source_password }}"
        vserver: "{{ source_vserver }}"
        volume: "{{ item.name }}"
        snapshot: "failover"
        state: present
      loop: "{{ filtered_volumes }}"

    - name: Update SnapMirror relationships for filtered volumes on SVM2
      netapp.ontap.na_ontap_snapmirror:
        hostname: "{{ target_host }}"
        username: "{{ target_username }}"
        password: "{{ target_password }}"
        dest_vserver: "{{ target_vserver }}"
        dest_volume: "{{ item.name }}"
        state: present
        update: true
      loop: "{{ filtered_volumes }}"
